# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='cash_reserves',
            field=models.IntegerField(choices=[(1, 'Less than two months.'), (2, 'Two to three months.'), (3, 'Three to five months.'), (4, 'Six months or more.')]),
        ),
        migrations.AlterField(
            model_name='risk',
            name='investment_experience',
            field=models.IntegerField(choices=[(1, 'None.'), (2, 'I have little background in purchasing stocks, some mutual funds.'), (3, 'I am comfortable with purchasing mutual funds, bonds, and stocks.'), (4, 'I have extensive investment experience with mutual funds, bonds, stocks, and derivatives.')]),
        ),
        migrations.AlterField(
            model_name='risk',
            name='investment_return',
            field=models.IntegerField(choices=[(1, 'Less than half of the market, however preserving capital is my primary goal.'), (2, 'Half of the market but protecting against potential losses by a riskier portfolio is not preferred.'), (3, '15-20% by accepting a sufficient amount of risk.'), (4, 'More than 20% by investing in an investment portfolio more risky than the market.')]),
        ),
        migrations.AlterField(
            model_name='risk',
            name='market_loss',
            field=models.IntegerField(choices=[(1, 'None.'), (2, '5% or less.'), (3, '10% or less.'), (4, 'It does not matter as long as the investments are appropriate for my objective.')]),
        ),
        migrations.AlterField(
            model_name='risk',
            name='time_horizont',
            field=models.IntegerField(choices=[(1, 'Five years or less.'), (2, 'Six to ten years.'), (3, 'Ten to fifteen years.'), (4, 'Greater than fifteen years.')]),
        ),
    ]
